### ISSUE TITLE
I can request associated (= configured) models of a task, but not the associated properties

### ISSUE THREAD

**Issue by thendrich** [KE-works/pykechain#149]
See http://pykechain.readthedocs.io/en/latest/api/models.html?highlight=assoc#pykechain.models.Activity.associated_parts

This gives me the associated models, but it's the properties I'm after. Also I'd like to see for each property if it's configured as View or Edit.

cc: @jberends

**Comment by jberends** [comment]
Indeed the current is to give back all the 'parts' (models+instances) that have associated properties configured. The properties of those parts are not filtered.

Let us check how to improve this.

**Comment by raduiordache** [comment]
@jberends I would say there is no point in doing this anymore, as the associated_parts() also have the properties filtered. And the properties themselves have output=True or False depending on whether they are editable or viewable only. I have discussed it with @thendrich and he agrees that he then has everything he needs. I am not sure what changed between July 10th and now but somehow it fixed by itself.

Can you double check just to confirm my findings and then close this issue?

Also, I have found some problems in the tests of #96 . I will commit my fixed in the branch related to this story and will make a pull request.

**Comment by jberends** [comment]
okay, lets move this into 1.10.1
