### ISSUE TITLE
I want to EDIT a currently existin widget's config

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#230]
Currently if I want to edit the config of a json widget. I have to find that widget, delete that widget and add a new json widget which is inserted at the button to "update" it. Could there be an edit function for a json widget? In which I can change specific attribute values

**Comment by jberends** [comment]
I showed you a workaround for this:

1. Put the customization in its own variable: `cust = activity.customization()`
1. take the n'th widget in the widget list `w = cust.widgets()[n]`
2. update the widget in place `w.update({})`
3. resave the full list of widgets using `cust._save_customization()`

Due to the way python works (reference to the widget remains part of the list from which you took the widget), the widget is updated in place.

**Comment by raduiordache** [comment]
Mooie solutie.
