### ISSUE TITLE
add ability to set reference part/property value

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#41]

**Comment by jberends** [comment]
I have thought about this, but as this reference value is simply the 'id' of the refered part(instance) and because the KEC API (should) handle(s) the validation that the instances is indeed of the model defined in the reference property model (value), the behaviour falls back to the default case of

```
    ref_prop.value = part_instance.id
```

**Comment by wilcoschoneveld** [comment]
Excuse me for reopening, but I think at least we should add some documentation for this? I'll come back to this later

**Comment by wilcoschoneveld** [comment]
#52

**Comment by jberends** [comment]
oops, sorry for that. I thought that we covered it.

We could make a jupyter notebook example for it if you want.
