### ISSUE TITLE
Move the dk functiality to copy move entire processes to pykechain.

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#524]
Basically copy paste DK core functionality, as we can now reuse it on many other places

**Comment by raduiordache** [comment]
Not feasible, I am afraid, DK works the way it does because it expects a certain structure which Pykechain, through its inherent flexibility, cannot offer. Moving empty or not connected to data activities is fine, but do you do when data is connected? How and where do you move those parts? What if it is another (with very different data-structure) scope? All this requires a design because you are making multiple calls to the API in a certain sequence, while also trying to cover all the tricky edge-cases.

Don't want to be the party pooper, but I don't think this is the purpose of Pykechain.
