### ISSUE TITLE
provide way to make requests to KE-chain in a parallel fashion (Thread pool)

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#53]
We have a case that there is code that loops over the following usecase many times

1. create a part from a model under a parent
2. get the part and update its properties

we know the model_id and know the parent_id and have a list of dicts to update each part.

As pykechain is synchronously calling KEC we can speed up bulk creation of the parts dramatically by usuing requests in e.g.  threadpool. 

solution ways:
1. bulk create and update in pyke, with a threadpool of parallel requests using part.add and part.update methods in sequence
2. create the desired KEC api endpoint to bulk update a single part (detail route) or bulk create parts with their properties (list route).

As we cannot control KEC code from this repo we could provide the parallel connection solution path.

sources:
* https://github.com/kennethreitz/grequests
* http://docs.python-requests.org/en/master/user/advanced/#blocking-or-non-blocking

**Comment by wilcoschoneveld** [comment]
I like the idea and great prototype! However, since initial testing does not indicate a significant improvement in speed, I would suggest to leave it out for now. Introducing asynchronous calls to pykechain leads to a whole new branch of spaghetti. What are your thoughts?

Is the single endpoint for updating multiple properties in a single part already prototyped and evaluated? This would change the implementation of `Part.update` to a single call instead of a for-loop.

**Comment by jberends** [comment]
I agree on all you say

findings:
1. architecture of client needs to change to allow for async processing
2. looses compatibility with py2.7 (pypy)
3. end-users of the api need to be aware of this stuff (which they really dont)
4. authority to handle bulk needs to shift to KEC. If KEC provides faster part editing than there is no need to do this async

We are working on the bulk editing feature in this sprint (see Jira), so I will ensyre the proper endpoints are in place there we can connect to.

**Comment by jberends** [comment]
I suggest not to do this.
